:- module(pure, []).

/** <module> Enables use of Pure CSS framework
*/

%  http://yui.github.io/skinbuilder/?mode=pureindex.html?opt=swi,457387,ffffff,1,1,20,1.5&h=0,-30,60&n=0,-30,75&l=0,-30,80&b=0,-30,90&mode=pure")
%
:- use_module(library(http/html_write)).
:- use_module(library(http/html_head)).
:- use_module(library(htmlutils)).

:- set_prolog_flag(double_quotes,string).

:- setting(yui_base, string, "http://yui.yahooapis.com", "Base URL for YUI loader (borked)").
% :- setting(yui_base, string, "https://yui-s.yahooapis.com", "Base URL for YUI loader").

http:location(pure,"//yui.yahooapis.com/pure/0.5.0",[]).
http:location(purecss,"//purecss.io/combo/1.16.5?",[]).

:- html_resource(purecss("css/layouts/side-menu.css"), [requires(pure("pure.min.css"))]).
:- html_resource(weblib("pure/pure-skin-plum.css"), [requires(pure("pure-min.css"))]).

user:head(pure(_,_),Head) --> !,
   html(head([ \style("//yui.yahooapis.com/pure/0.5.0/pure-min.css")
             , \style("//yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css")
             , \style("/weblib/pure/pure-skin.css")
             , meta([name(viewport), content("width-device-width,initial-scale=1")]) 
             | Head ])).


cdata(Content) -->
   (  {html_current_option(dialect(xhtml))}
   -> ['<![CDATA[\n'], html(\Content), [']]>']
   ;  html(\Content)
   ).

%% javascript(+Phrase)// is det.
%  Emit SCRIPT element containing the code generated by DCG goal
%  Phrase. This must produce a list of tokens as generated by html//1
%  and understood by print_html/1.
javascript(Code) -->
   html(script(type('text/javascript'), \cdata(Code))).

activate_dropdowns(DivId,ULId) -->
   {setting(yui_base, YUIBase)},
   javascript(
      [ "YUI({ classNamePrefix: 'pure', combine: true, comboBase: '~w/combo?' 
             }).use('gallery-sm-menu', function (Y) {\n"-[YUIBase]
      , "  var horizontalMenu = new Y.Menu({\n"
      , "     container         : '#~w',\n"-[DivId]
      , "     sourceNode        : '#~w',\n"-[ULId]
      , "     orientation       : 'horizontal',\n"
      , "     hideOnOutsideClick: false,\n"
      , "     hideOnClick       : false,\n"
      , "     showdelay         : 125,\n"
      , "  });\n"
      , "  horizontalMenu.render();\n"
      , "  horizontalMenu.show();\n"
      , "});"
      ]).

user:body(pure(1,Nav),Body) --> !,
   { setting(htmlutils:appname, AppName) },
	html(body([ div([id("layout"),class("pure-g")]
             , [ div(class("pure-u-1-4"), \vmenu(AppName,Nav))
               , div(class("content pure-u-3-4"), [
                   div(class(content),Body)
                 , div(class(footer),\hmenu(AppName,Nav))
                 ])
               ])
             ])).

user:body(pure(2,Nav),Body) --> !,
   { setting(htmlutils:appname, AppName) },

   use_font("Source Sans Pro",sourcepro),
   % use_font("Open Sans",opensans),
   % use_font("Quattrocento Sans",quattrocento),
   % html_requires(purecss("css/main-grid.css&/css/main.css&/css/menus.css&/css/rainbow/baby-blue.css")),
   html_requires(purecss("css/layouts/side-menu.css")),
	html(body(div(id(layout), 
             [ a([href="#menu", id="menuLink", class="menu-link"],span([]))
             , div(id(menu),\vmenu(AppName,Nav))
             , div(id(main),
               [ div(class(header), h1("Header"))
               , div(class(content), [div(Body),div(class=footer,\hmenu(AppName,Nav))])
               ])
             , \script(purecss("js/ui.js"))
             ]))).

button_link(Ref,Content) --> 
   html(a([class(['pure-button','pure-button-primary']),href(Ref)],Content)).

menu(Classes,Content) --> 
   html(div(class(['pure-menu', 'pure-menu-open'|Classes]), Content)).
% Add pure-menu-selected to active item
hmenu(Heading,Items) --> 
   menu(['pure-menu-horizontal'], [a([href='.',class="pure-menu-heading"],Heading), \Items]).

vmenu(Heading,Items) --> 
   menu([], [a([href='.',class="pure-menu-heading"],Heading), \Items]).

hmenu_with_dropdowns(Items) --> 
   % html_requires("//yui.yahooapis.com/3.17.2/build/yui/yui-min.js"),
   {setting(yui_base,YUIBase)},
   {string_concat(YUIBase,"/3.17.2/build/yui/yui-min.js",YUIJS)},
   html_requires(YUIJS),
   {gensym(div,DivID), gensym(ul,ULID)},
   html(div(id=DivID,ul(id=ULID,\Items))),
   activate_dropdowns(DivID,ULID).
